// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keqlocalzmdojnsgwoqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcWxvY2Fsem1kb2puc2d3b3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzk4ODAsImV4cCI6MjA2NjY1NTg4MH0.Q4HH2UccNQ-tdqOZbuA-qtp8fHuZNlsBZuUybCu_IfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});